# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Balance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, client_id: str = None, product_id: str = None, quantity: int = None):  # noqa: E501
        """Balance - a model defined in Swagger

        :param client_id: The client_id of this Balance.  # noqa: E501
        :type client_id: str
        :param product_id: The product_id of this Balance.  # noqa: E501
        :type product_id: str
        :param quantity: The quantity of this Balance.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'client_id': str,
            'product_id': str,
            'quantity': int
        }

        self.attribute_map = {
            'client_id': 'clientId',
            'product_id': 'productId',
            'quantity': 'quantity'
        }
        self._client_id = client_id
        self._product_id = product_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'Balance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Balance of this Balance.  # noqa: E501
        :rtype: Balance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> str:
        """Gets the client_id of this Balance.

        Client Identifier  # noqa: E501

        :return: The client_id of this Balance.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: str):
        """Sets the client_id of this Balance.

        Client Identifier  # noqa: E501

        :param client_id: The client_id of this Balance.
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def product_id(self) -> str:
        """Gets the product_id of this Balance.

        Product Identifier  # noqa: E501

        :return: The product_id of this Balance.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this Balance.

        Product Identifier  # noqa: E501

        :param product_id: The product_id of this Balance.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this Balance.

        Number of Units  # noqa: E501

        :return: The quantity of this Balance.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this Balance.

        Number of Units  # noqa: E501

        :param quantity: The quantity of this Balance.
        :type quantity: int
        """

        self._quantity = quantity
